/**
 * content/extractor.js — URL parsing and aweme-id extraction utilities.
 *
 * Douyin NEVER exposes a usable video URL on the <video> element itself —
 * that src is always a blob: URL generated by the media-source stack.
 * The real CDN URLs live in:
 *
 *   1. <script id="RENDER_DATA">  — URL-encoded JSON baked in by SSR.
 *   2. window._ROUTER_DATA / window.__INITIAL_STATE__ / window.__DATA__ etc.
 *      — other SSR globals injected at page load.
 *   3. Dynamic feed API responses captured by network.js as the user scrolls.
 *
 * All functions here are pure (no DOM side-effects, no state mutation) so they
 * can be unit-tested in isolation and imported by any module without risk of
 * accidental ordering issues.
 */

// ── URL cleaning & validation ─────────────────────────────────────────────────

/**
 * Normalize a raw URL string from Douyin's JSON data into a plain https:// URL.
 *
 * Douyin stores URLs in several encodings depending on the data source:
 *   - Percent-encoded  ("https%3A%2F%2F...")
 *   - Escaped backslashes from JSON serialisation ("https:\/\/...")
 *   - Protocol-relative ("//v3.douyinvod.com/...")
 *
 * Returns null if the input cannot be coerced into an http/https URL.
 *
 * @param {*} raw
 * @returns {string|null}
 */
export function cleanVideoUrl(raw) {
    if (!raw || typeof raw !== 'string') return null;
    let url = raw;

    // Percent-encoded URLs embedded directly in JSON strings
    if (url.startsWith('https%3A') || url.startsWith('http%3A')) {
        try { url = decodeURIComponent(url); } catch (e) { /* leave as-is */ }
    }

    // Escaped backslashes that appear when JSON is serialised inside
    // a URL-encoded outer layer (e.g. window._ROUTER_DATA)
    url = url.replace(/\\/g, '');

    // Protocol-relative links — always upgrade to https
    if (url.startsWith('//')) url = 'https:' + url;

    // Reject anything that still doesn't start with http (e.g. data:, blob:, ///)
    if (!url.startsWith('http')) return null;

    return url;
}

/**
 * Return true only for URLs that are almost certainly a video stream CDN link.
 *
 * Douyin data objects contain many url_list fields (cover images, avatars, API
 * endpoints, etc.).  This heuristic filters them down to video CDN links by
 * checking known video-CDN hostnames and rejecting known image/static-asset
 * patterns.  False negatives (missing a real video URL) are preferable to false
 * positives (downloading an image believing it to be a video).
 *
 * @param {string} url
 * @returns {boolean}
 */
export function looksLikeVideoUrl(url) {
    if (!url) return false;
    const lc = url.toLowerCase();

    // Reject image / static asset extensions
    if (/\.(png|jpe?g|webp|gif|svg|ico|css|js)(\?|$)/i.test(url)) return false;

    // Reject paths that are clearly not video streams
    if (lc.includes('/avatar/') || lc.includes('/cover/') || lc.includes('/img/')) return false;

    // Accept known video CDN hostnames or URL characteristics
    return (
        lc.includes('douyinvod.com')    ||
        lc.includes('amemv.com')        ||
        lc.includes('ixigua.com')       ||
        lc.includes('toutiao50.com')    ||
        lc.includes('pstatp.com')       ||
        lc.includes('.mp4')             ||
        lc.includes('.m3u8')            ||
        lc.includes('mime_type=video')  ||
        lc.includes('mime=video')
    );
}

// ── Recursive object traversal ────────────────────────────────────────────────

/**
 * Recursively walk an arbitrary Douyin data object to find a play_addr /
 * playAddr node and return all its url_list entries that look like video URLs.
 *
 * Priority walk order ensures we return play_addr (no watermark) before
 * download_addr (watermarked) — the caller gets the best available URL first.
 * A circular-reference guard (`visited` Set) prevents infinite recursion on
 * self-referential Douyin data structures.
 *
 * @param {*}      obj     - Arbitrary data object to search.
 * @param {number} depth   - Remaining recursion depth (starts at 12).
 * @param {Set}    visited - Already-visited object references.
 * @returns {string[]}     - List of cleaned CDN video URLs, best-first.
 */
export function extractPlayAddrUrls(obj, depth = 12, visited = new Set()) {
    if (!obj || depth <= 0) return [];
    if (typeof obj !== 'object') return [];

    // Avoid descending into DOM nodes or the window object — those are never
    // Douyin data structures but could cause infinite loops
    if (obj instanceof Element || obj instanceof HTMLDocument || obj === window) return [];
    if (visited.has(obj)) return [];
    visited.add(obj);

    let urls = [];

    // If THIS node is a play_addr / url_list container, harvest it directly
    // and return early — no need to recurse further into it
    if (obj.url_list && Array.isArray(obj.url_list)) {
        for (const u of obj.url_list) {
            const cleaned = cleanVideoUrl(u);
            if (cleaned && looksLikeVideoUrl(cleaned)) urls.push(cleaned);
        }
        if (urls.length > 0) return urls;
    }

    if (Array.isArray(obj)) {
        for (const item of obj) {
            const found = extractPlayAddrUrls(item, depth - 1, visited);
            if (found.length > 0) urls.push(...found);
        }
    } else {
        // Visit high-probability keys first so we return play_addr (no
        // watermark) before download_addr (watermarked) and skip the rest
        // of the tree as early as possible via the return-early above
        const priorityKeys = [
            'play_addr', 'playAddr', 'play_addr_h264',
            'video',
            'download_addr', 'downloadAddr',
        ];
        for (const key of priorityKeys) {
            if (obj[key]) {
                const found = extractPlayAddrUrls(obj[key], depth - 1, visited);
                if (found.length > 0) return found; // best match — stop here
            }
        }
        // Then scan all remaining keys for any other embedded URLs
        for (const key in obj) {
            if (priorityKeys.includes(key)) continue;
            try {
                const val = obj[key];
                if (val && typeof val === 'object') {
                    const found = extractPlayAddrUrls(val, depth - 1, visited);
                    if (found.length > 0) urls.push(...found);
                }
            } catch (e) { /* skip inaccessible properties */ }
        }
    }
    return urls;
}

/**
 * Walk an object tree looking for an aweme node whose aweme_id / awemeId
 * matches `id`.  Returns the matching aweme node so callers can then call
 * extractPlayAddrUrls() on exactly the right item rather than on the whole
 * tree (which might return a URL belonging to a different video).
 *
 * @param {*}      obj   - Root of the data tree to search.
 * @param {string} id    - The aweme_id to match.
 * @param {number} depth - Remaining recursion depth (starts at 10).
 * @param {Set}    visited
 * @returns {object|null}
 */
export function findAwemeById(obj, id, depth = 10, visited = new Set()) {
    if (!obj || depth <= 0 || typeof obj !== 'object') return null;
    if (obj instanceof Element || obj === window) return null;
    if (visited.has(obj)) return null;
    visited.add(obj);

    // An aweme node has both an ID field AND a video/play_addr child
    if ((obj.aweme_id === id || obj.awemeId === id) && (obj.video || obj.play_addr)) {
        return obj;
    }

    if (Array.isArray(obj)) {
        for (const item of obj) {
            const found = findAwemeById(item, id, depth - 1, visited);
            if (found) return found;
        }
    } else {
        for (const key in obj) {
            try {
                const val = obj[key];
                if (val && typeof val === 'object') {
                    const found = findAwemeById(val, id, depth - 1, visited);
                    if (found) return found;
                }
            } catch (e) { /* skip inaccessible */ }
        }
    }
    return null;
}

// ── Page-level aweme-id extraction ────────────────────────────────────────────

/**
 * Parse the aweme_id (Douyin's internal video ID) from the current page URL.
 *
 * Single-video URLs:    https://www.douyin.com/video/7379…
 * Modal/share URLs:     https://www.douyin.com/…?modal_id=7379…
 *
 * Returns null on feed/home pages where no specific video is in the URL.
 *
 * @returns {string|null}
 */
export function getAwemeIdFromPageUrl() {
    const m =
        location.href.match(/\/video\/(\d+)/) ||
        location.href.match(/modal_id=(\d+)/);
    return m ? m[1] : null;
}

/**
 * Return true when the current page shows a scrollable feed with multiple
 * videos (home, discover, follow).  On these pages there is no authoritative
 * video ID in the URL so the caller must rely on element-level ID extraction.
 *
 * @returns {boolean}
 */
export function isFeedPage() {
    if (document.querySelectorAll('video').length > 1) return true;
    const path = location.pathname;
    return (
        path === '/' ||
        path.startsWith('/discover') ||
        path.startsWith('/follow') ||
        path.startsWith('/recommend')
    );
}

/**
 * Walk up the DOM ancestry of a <video> element to find the aweme_id.
 *
 * Douyin's React tree places a `data-e2e-vid` attribute on the slider
 * container that wraps each feed video (roughly 5–15 levels up).  As a
 * fallback the class name sometimes contains "video_<id>".
 *
 * @param {HTMLVideoElement} videoEl
 * @returns {string|null}
 */
export function getAwemeIdFromVideoElement(videoEl) {
    if (!videoEl) return null;
    let el = videoEl;
    for (let i = 0; i < 20 && el && el !== document.body; i++) {
        // Primary: data-e2e-vid attribute set by Douyin's rendering layer
        if (el.dataset && el.dataset.e2eVid) return el.dataset.e2eVid;

        // Backup: some older builds encode the ID in a className like "video_7379…"
        if (el.className && typeof el.className === 'string') {
            const m = el.className.match(/video_(\d{15,})/);
            if (m) return m[1];
        }
        el = el.parentElement;
    }
    return null;
}

// ── SSR / page-data extraction ────────────────────────────────────────────────

/**
 * Scan every SSR data source baked into the page to find the CDN download URL
 * for the given aweme_id (or for the only video on a single-video page).
 *
 * Sources tried in order (most-reliable first):
 *   1. <script id="RENDER_DATA"> — always present on video detail pages.
 *   2. window._ROUTER_DATA       — newer Next.js-based Douyin pages.
 *   3. window.__INITIAL_STATE__, window.__DATA__, etc.
 *   4. Brute-force scan of all inline <script> tags that mention play_addr.
 *
 * When `targetAwemeId` is known the function does an ID-matched search so it
 * returns the URL for exactly the right video rather than whatever happens to
 * appear first in the data tree.
 *
 * @param {string|null} targetAwemeId
 * @returns {string|null}
 */
export function getVideoUrlFromPageData(targetAwemeId) {
    // Resolve the best aweme_id we have: caller-supplied > URL-derived
    const awemeId = targetAwemeId || getAwemeIdFromPageUrl();
    const allPlayUrls = []; // accumulates fallback URLs when no ID match is possible

    /**
     * Search a single data source.
     * When awemeId is known, ONLY returns a URL belonging to that aweme so we
     * never accidentally show the URL for a different video.
     */
    function searchDataSource(data) {
        if (!data) return null;
        if (awemeId) {
            const matching = findAwemeById(data, awemeId);
            if (matching) {
                const urls = extractPlayAddrUrls(matching);
                if (urls.length > 0) return urls[0];
            }
            // Don't fall through to generic extraction when we have an ID —
            // a generic match might return a URL from the wrong video
            return null;
        }
        // No ID available — fall back to generic (less precise) extraction
        const urls = extractPlayAddrUrls(data);
        return urls.length > 0 ? urls[0] : null;
    }

    // ── Source 1: <script id="RENDER_DATA"> ────────────────────────────────
    // Always try this first — it is injected by Douyin's SSR and is the most
    // reliable source on detail pages
    try {
        const el = document.getElementById('RENDER_DATA');
        if (el) {
            const raw = el.textContent || el.innerText || '';
            const data = JSON.parse(decodeURIComponent(raw));
            const result = searchDataSource(data);
            if (result) return result;
            if (!awemeId) { allPlayUrls.push(...extractPlayAddrUrls(data)); }
        }
    } catch (e) { /* malformed JSON — skip */ }

    // ── Source 2: window._ROUTER_DATA ──────────────────────────────────────
    // Present on newer Douyin pages that use a Next.js-style router
    try {
        if (window._ROUTER_DATA) {
            const result = searchDataSource(window._ROUTER_DATA);
            if (result) return result;
            if (!awemeId) { allPlayUrls.push(...extractPlayAddrUrls(window._ROUTER_DATA)); }
        }
    } catch (e) { /* not available on this page — skip */ }

    // ── Source 3: Other known SSR globals ──────────────────────────────────
    const ssrGlobals = [
        window._SSR_HYDRATED_DATA,
        window.__INITIAL_STATE__,
        window.__DATA__,
        window.render_data,
    ];
    for (const data of ssrGlobals) {
        if (!data) continue;
        try {
            const result = searchDataSource(data);
            if (result) return result;
            if (!awemeId) { allPlayUrls.push(...extractPlayAddrUrls(data)); }
        } catch (e) { /* skip */ }
    }

    // ── Source 4: Brute-force inline <script> scan ─────────────────────────
    // Last resort: scan every non-src script tag for JSON that mentions
    // play_addr.  Slow but catches edge cases where Douyin changes its
    // global variable names
    try {
        const scripts = document.querySelectorAll('script[type="application/json"], script:not([src])');
        for (const script of scripts) {
            if (script.id === 'RENDER_DATA') continue; // already checked above
            const text = script.textContent || '';
            if (!text.includes('play_addr') && !text.includes('playAddr') && !text.includes('url_list')) continue;
            try {
                const data = JSON.parse(text.startsWith('%') ? decodeURIComponent(text) : text);
                const result = searchDataSource(data);
                if (result) return result;
                if (!awemeId) { allPlayUrls.push(...extractPlayAddrUrls(data)); }
            } catch (e) { /* not valid JSON — skip */ }
        }
    } catch (e) { /* querySelectorAll failed — skip */ }

    return allPlayUrls.length > 0 ? allPlayUrls[0] : null;
}
